# Generated by Django 3.1.1 on 2020-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creating_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
