# Generated by Django 3.1.1 on 2020-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
